
set(CUDA_OPTION)
if(CMAKE_CUDA_COMPILER_ID STREQUAL "NVIDIA")
	set(CUDA_OPTION "CUDA=${CMAKE_CUDA_TOOLKIT_INCLUDE_DIRECTORIES}/../")
endif()

superbuild_add_project(
  gdrcopy 
  DEPENDS cuda
  BUILD_IN_SOURCE 1
  CONFIGURE_COMMAND "" 
  BUILD_COMMAND make -j${SUPERBUILD_PROJECT_PARALLELISM} -l${SUPERBUILD_PROJECT_PARALLELISM} PREFIX=<INSTALL_DIR> ${CUDA_OPTION} all
  INSTALL_COMMAND make install
  )

