

superbuild_add_project(
  nccl
  DEPENDS cuda 
  BUILD_IN_SOURCE 1
  PATCH_COMMAND "" 
  CONFIGURE_COMMAND "" 
  BUILD_COMMAND make -j${SUPERBUILD_PROJECT_PARALLELISM} -l${SUPERBUILD_PROJECT_PARALLELISM} src.build PREFIX=<INSTALL_DIR>
  INSTALL_COMMAND make install PREFIX=<INSTALL_DIR>
  )

