steps:
  - group: ":cpp: Build"
    key: "build"
    steps:
    - label: "Build Linux :linux:"
      command: "SSH_AUTH_SOCK=/dev/null ./build.sh"
      plugins:
      - git-clean#v1.0.0:
          flags: "-ffdqx --exclude=vcpkg_cache"
      key: "build-linux"
      artifact_paths: 
      - "*.tar.gz"