steps:
      - label: ":cpp: Build"
        command: .buildkite/build.sh
        artifact_paths:
           - "*.tar.gz"
        env:
          CCACHE_DIR: /ccache
          CCACHE_MAXSIZE: 40G
        agents:
          digest: "700935a1253dd3cdac352dfc141242c6f32866b3f94f456e5efd57275a86f89f"
          queue: "zcfd"
