#!/bin/bash

source /opt/rh/devtoolset-8/enable
source /opt/rh/rh-git218/enable
source /opt/intel/compilers_and_libraries_2020.2.254/linux/bin/compilervars.sh intel64

export PATH=/usr/lib64/openmpi3/bin:$PATH

exec $*
